CREATE TABLE IF NOT EXISTS supplier_fitment_candidates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    supplier_item_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NULL,
    raw_make VARCHAR(120) NULL,
    raw_model VARCHAR(120) NULL,
    raw_generation VARCHAR(120) NULL,
    raw_engine VARCHAR(120) NULL,
    raw_year_from INT NULL,
    raw_year_to INT NULL,
    raw_text TEXT NULL,
    matched_vehicle_id BIGINT UNSIGNED NULL,
    confidence_label VARCHAR(40) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    review_note TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    INDEX idx_sfc_supplier_item_id (supplier_item_id),
    INDEX idx_sfc_product_id (product_id),
    INDEX idx_sfc_matched_vehicle_id (matched_vehicle_id),
    INDEX idx_sfc_status (status),
    INDEX idx_sfc_reviewed_by_user_id (reviewed_by_user_id),
    CONSTRAINT fk_sfc_supplier_item FOREIGN KEY (supplier_item_id) REFERENCES supplier_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_sfc_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT fk_sfc_matched_vehicle FOREIGN KEY (matched_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
    CONSTRAINT fk_sfc_reviewed_by_user FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_sfc_status CHECK (status IN ('pending', 'approved', 'rejected', 'skipped')),
    CONSTRAINT chk_sfc_confidence_label CHECK (confidence_label IS NULL OR confidence_label IN ('exact', 'likely', 'unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
