CREATE TABLE IF NOT EXISTS ai_product_import_drafts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    source_url TEXT NOT NULL,
    source_domain VARCHAR(190) NULL,
    source_type VARCHAR(60) NULL,
    status VARCHAR(40) NOT NULL,
    import_title VARCHAR(255) NULL,
    import_brand VARCHAR(190) NULL,
    import_sku VARCHAR(120) NULL,
    import_short_description TEXT NULL,
    import_description LONGTEXT NULL,
    import_price DECIMAL(12,2) NULL,
    import_currency VARCHAR(12) NULL,
    import_stock_text VARCHAR(190) NULL,
    import_image_urls LONGTEXT NULL,
    import_attributes LONGTEXT NULL,
    import_raw_text LONGTEXT NULL,
    ai_summary LONGTEXT NULL,
    ai_structured_payload LONGTEXT NULL,
    review_note TEXT NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    KEY idx_ai_import_status (status),
    KEY idx_ai_import_created_by (created_by_user_id),
    KEY idx_ai_import_reviewed_by (reviewed_by_user_id),
    KEY idx_ai_import_source_domain (source_domain)
);
