CREATE TABLE IF NOT EXISTS ai_product_enrichment_suggestions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT UNSIGNED NOT NULL,
    suggestion_type VARCHAR(60) NOT NULL,
    source_context VARCHAR(60) NULL,
    input_snapshot LONGTEXT NULL,
    suggested_title VARCHAR(255) NULL,
    suggested_short_description TEXT NULL,
    suggested_description LONGTEXT NULL,
    suggested_attributes LONGTEXT NULL,
    suggested_seo_title VARCHAR(255) NULL,
    suggested_meta_description TEXT NULL,
    ai_summary LONGTEXT NULL,
    status VARCHAR(40) NOT NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    KEY idx_ai_enrichment_product_id (product_id),
    KEY idx_ai_enrichment_status (status),
    KEY idx_ai_enrichment_suggestion_type (suggestion_type),
    KEY idx_ai_enrichment_created_by (created_by_user_id),
    CONSTRAINT fk_ai_enrichment_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_enrichment_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_enrichment_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
