CREATE TABLE IF NOT EXISTS ai_fitment_suggestions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT UNSIGNED NOT NULL,
    suggested_vehicle_id BIGINT UNSIGNED NOT NULL,
    source_type VARCHAR(60) NOT NULL,
    source_reference_id BIGINT UNSIGNED NULL,
    confidence_label VARCHAR(40) NOT NULL DEFAULT 'unknown',
    suggestion_reason TEXT NULL,
    input_snapshot LONGTEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    created_by_user_id BIGINT UNSIGNED NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    INDEX idx_ai_fitment_suggestions_product_id (product_id),
    INDEX idx_ai_fitment_suggestions_vehicle_id (suggested_vehicle_id),
    INDEX idx_ai_fitment_suggestions_status (status),
    INDEX idx_ai_fitment_suggestions_source_type (source_type),
    INDEX idx_ai_fitment_suggestions_confidence_label (confidence_label),
    CONSTRAINT fk_ai_fitment_suggestions_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_fitment_suggestions_vehicle FOREIGN KEY (suggested_vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_fitment_suggestions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_fitment_suggestions_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_ai_fitment_suggestions_status CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT chk_ai_fitment_suggestions_source_type CHECK (source_type IN ('supplier_fitment_candidate', 'ai_import_draft', 'product_text', 'mixed')),
    CONSTRAINT chk_ai_fitment_suggestions_confidence_label CHECK (confidence_label IN ('exact', 'likely', 'unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
